version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:3.0.5

  api:
    build: ./api
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    ports:
      - 80
    volumes:
      - ./api:/myapp
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  api_proxy:
    image: nginx:1.13
    volumes:
      - ./api_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - api

  bff:
    build: ./bff
    command: npm run dev
    ports:
      - 80
    depends_on:
      - api_proxy
    volumes:
      - ./bff:/myapp

  bff_proxy:
    image: nginx:1.13
    volumes:
      - ./bff_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - bff

volumes:
  db-data:
    driver: local
