version: '2'
services:
  # db:
  #   image: mysql:5.7.17
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./docker/mysql/volumes:/var/lib/mysql
  #   extends:
  #     file: ./docker/mysql/password.yml
  #     service: password

  api:
    build: ./api
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    ports:
      - 80
    environment:
      RAILS_ENV: development
    # extends:
    #   file: ./docker/mysql/password.yml
    #   service: password
    # depends_on:
    #   - db
    volumes:
      - ./api:/myapp

  api_proxy:
    image: nginx:1.13
    volumes:
      - ./api_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - api

  bff:
    build: ./bff
    command: npm run dev
    ports:
      - 80
    depends_on:
      - api_proxy
    volumes:
      - ./bff:/myapp

  bff_proxy:
    image: nginx:1.13
    volumes:
      - ./bff_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - bff
