default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  url: <%= ENV["DATABASE_URL"] %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: my-nextjs-bff-boilerplate_development

test:
  <<: *default
  database: my-nextjs-bff-boilerplate_test

production:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: my-nextjs-bff-boilerplate_production
  socket: /tmp/mysql.sock
